language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script: pytest
notifications:
  slack: luccsresearch:cEA9llY9UxQJymallfIwx9ar
